FROM python:3.11

WORKDIR /client

# Скопировать файл requirements.txt и установить зависимости
COPY requirements.txt /client/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Скопировать все остальные файлы
COPY . /client

EXPOSE 5000

CMD ["python", "app.py"]
