FROM python:3.11

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app
COPY wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh
#для запуска FLAKE8 
RUN pip install flake8
RUN  flake8 /app/fishing_project
#для bandit
RUN pip install bandit
RUN bandit -r /app/fishing_project
#для трюфлога
RUN pip install trufflehog
RUN trufflehog --max_depth 50 --regex --json https://github.com/gdumfi/FIshid

EXPOSE 8000

CMD ["/app/wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
