# Generated by Django 5.1.2 on 2024-10-22 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fisherman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FishCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.fish')),
            ],
        ),
        migrations.CreateModel(
            name='FishingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight', models.FloatField()),
                ('weather_conditions', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('poor', 'Poor')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.captain')),
                ('fish_catches', models.ManyToManyField(through='fishing.FishCatch', to='fishing.fish')),
                ('fishermen', models.ManyToManyField(to='fishing.fisherman')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.ship')),
            ],
        ),
        migrations.AddField(
            model_name='fishcatch',
            name='fishing_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.fishingreport'),
        ),
    ]
