# Generated by Django 5.1.2 on 2024-10-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_remove_fisherman_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captain',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='captain',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
