# Generated by Django 5.1.2 on 2024-10-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0005_weathercondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingreport',
            name='weather_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.weathercondition'),
        ),
    ]
