# Generated by Django 5.1.2 on 2024-10-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisherman',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fisherman',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='fisherman',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='fisherman',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
