# Generated by Django 5.1.2 on 2024-10-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0004_remove_fishingreport_total_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
